# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170101_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
    ]
